export const suggestionResult = {
  query: 'Short',
  suggested: {
    text: 'short',
    type: 'exact',
    completed: [],
    source: 'popular-query',
  },
  alternatives: [
    {
      text: 'shorts',
      type: 'completed',
      completed: [
        {
          token: 'shorts',
          query: 'short',
          type: 'prefix',
        },
      ],
      source: 'popular-query',
    },
    {
      text: 'shorts5.5',
      type: 'completed',
      completed: [
        {
          token: 'shorts5.5',
          query: 'short',
          type: 'prefix',
        },
      ],
      source: 'popular-query',
    },
    {
      popularity: 322,
      text: 'golf shorts',
    },
    {
      popularity: 312,
      text: 'fleece shorts',
    },
    {
      popularity: 268,
      text: 'mens shorts',
    },
  ],
}

export const searchResult = {
  pagination: {
    totalResults: 556,
    begin: 1,
    end: 6,
    currentPage: 1,
    totalPages: 93,
    previousPage: 0,
    nextPage: 2,
    perPage: 6,
    defaultPerPage: 40,
  },
  sorting: {
    options: [
      {
        field: 'relevance',
        direction: 'desc',
        label: 'Best Match',
      },
      {
        field: 'ga_unique_purchases',
        direction: 'desc',
        label: 'Best Selling',
      },
      {
        field: 'ss_days_since_published',
        direction: 'asc',
        label: 'Newest',
      },
      {
        field: 'title',
        direction: 'asc',
        label: 'Name: A - Z',
      },
      {
        field: 'title',
        direction: 'desc',
        label: 'Name: Z - A',
      },
      {
        field: 'ss_price',
        direction: 'asc',
        label: 'Price: Low to High',
      },
      {
        field: 'ss_price',
        direction: 'desc',
        label: 'Price: High to Low',
      },
    ],
  },
  resultLayout: 'grid',
  results: [
    {
      brand: 'Chubbies Shorts',
      handle: 'the-ruggeds-6-everywear-short',
      id: '8c039cbaa52f178ff18ef936600bfac2',
      imageUrl:
        'https://cdn.shopify.com/s/files/1/0077/0432/products/KHAKINATORS_6_EVERYWEAR_SHORT__LS_029203-01_0887_600x600.webp?v=1670450020',
      intellisuggestData:
        'eJwEwN0NgCAMBOBbqMm1UCzj8GPUJyO6f_werx4JMalFe5HueUjW4dI8U-bOoVtEtUa8570-0KoxCdWgUBDuBce65h8AAP__q4URfQ',
      intellisuggestSignature: 'c6aa9e49621705366071321a916832af58758764d64c195caad73ed4eff9370f',
      mfield_custom_fields_inseam_text: '6&quot;',
      msrp: '64.5',
      name: 'The Khakinators 6&quot; (Everywear Stretch)',
      price: '64.5',
      product_type_unigram: 'khakinators',
      sku: '029203-012',
      ss_available: '1',
      ss_inventory_count: '3714',
      ss_sizes:
        '[{&quot;label&quot;:&quot;S&quot;,&quot;variant_id&quot;:31206836338761,&quot;available&quot;:475},{&quot;label&quot;:&quot;M&quot;,&quot;variant_id&quot;:31206836371529,&quot;available&quot;:1226},{&quot;label&quot;:&quot;L&quot;,&quot;variant_id&quot;:31206836404297,&quot;available&quot;:1307},{&quot;label&quot;:&quot;XL&quot;,&quot;variant_id&quot;:31206836437065,&quot;available&quot;:576},{&quot;label&quot;:&quot;XXL&quot;,&quot;variant_id&quot;:31206836469833,&quot;available&quot;:130}]',
      ss_tags: [
        '1.4.2020',
        '6incheverywear2.0desc',
        'allproductsnogiftcards',
        'auto:lowinventory',
        'availablein',
        'backtoschool',
        'basicsale30',
        'bundlecasualshorts',
        'bundleswimshorts',
        'butterybros',
        'buy2bundle',
        'casualbestsellers',
        'casualbestsellers',
        'casualcombo',
        'casualbestsellersale',
        'casualbottomsfp',
        'casualbundle',
        'category:shorts',
        'ces',
        'collection:everyweargolfcollection',
        'colorapplication:solid',
        'deletefathersday',
        'escape',
        'everydaybasics',
        'everywearathl21',
        'everywearshorts',
        'extra30',
        'fabric:everywear',
        'fathersday21',
        'filtercolor:beige',
        'filterinseam:6&quot;',
        'foundersfavorites',
        'fpcasualbottoms',
        'fullpricebundle',
        'giftbundle21',
        'giftbundle21casual',
        'golf',
        'golfdad',
        'holidaycasualpromo',
        'influencercasual',
        'khaki',
        'khakicollection',
        'khakinatorswatch',
        'lining:noliner',
        'loopreturns',
        'onsitecasual',
        'otb:pfd',
        'restocked',
        'restockeditem',
        'season:fa20',
        'shortsforlake',
        'silhouette:everywear',
        'sitebundle',
        'sitewide30',
        'sitewide30',
        'skuonsite',
        'springbreak',
        'stretchcasualdesc',
        'style:everywearshorts6',
        'swatchloadcasual',
        'tailgate21',
        'type:hybrid',
        'vacationer',
        'ycrf_casual',
        'ygroup_everywear',
      ],
      tags: [
        '1.4.2020',
        '6incheverywear2.0desc',
        'allproductsnogiftcards',
        'auto:low-inventory',
        'available in',
        'backtoschool',
        'BASICSALE30',
        'bundle--casual-shorts',
        'bundle--swim-shorts',
        'buttery-bros',
        'Buy2Bundle',
        'casual-best-sellers',
        'casual-bestsellers',
        'casual-combo',
        'casualbestseller-sale',
        'casualbottoms-FP',
        'CASUALBUNDLE',
        'CATEGORY: SHORTS',
        'CES',
        'COLLECTION:everywear-golf-collection',
        'ColorApplication:SOLID',
        'deletefathersday',
        'escape',
        'everyday-basics',
        'everywearathl21',
        'everywearshorts',
        'EXTRA30',
        'Fabric:EVERYWEAR',
        'fathersday21',
        'filter-color:beige',
        'filter-inseam:6&quot;',
        'FoundersFavorites',
        'FPCasualBottoms',
        'FULLPRICEBUNDLE',
        'giftbundle21',
        'giftbundle21casual',
        'golf',
        'golf-dad',
        'HOLIDAYCASUALPROMO',
        'influencer-casual',
        'Khaki',
        'khakicollection',
        'khakinatorswatch',
        'Lining:NO LINER',
        'loopreturns',
        'onsite-casual',
        'OTB: PFD',
        'restocked',
        'restockeditem',
        'Season:FA20',
        'shorts-for-lake',
        'Silhouette:EVERYWEAR',
        'sitebundle',
        'SITEWIDE-30',
        'sitewide30',
        'sku-onsite',
        'spring-break',
        'stretchcasualdesc',
        'style:everywear-shorts-6',
        'SWATCHLOAD-CASUAL',
        'tailgate21',
        'Type:HYBRID',
        'vacationer',
        'YCRF_CASUAL',
        'YGroup_EVERYWEAR',
      ],
      tags_filter_color: ['beige'],
      tags_filter_inseam: ['6&quot;'],
      thumbnailImageUrl:
        'https://cdn.shopify.com/s/files/1/0077/0432/products/KHAKINATORS_6_EVERYWEAR_SHORT__LS_029203-01_0887_600x600.webp?v=1670450020',
      uid: '4374498541641',
      url: 'https://chubbies.myshopify.com/products/the-ruggeds-6-everywear-short',
      variant_id: [
        '31206836338761',
        '31206836371529',
        '31206836404297',
        '31206836437065',
        '31206836469833',
      ],
      variant_inventory_policy: 'deny',
      variant_inventory_quantity: ['475', '1226', '1307', '576', '130'],
      variant_size: ['S', 'M', 'L', 'XL', 'XXL'],
      variant_title: ['S', 'M', 'L', 'XL', 'XXL'],
    },
    {
      brand: 'Chubbies Shorts',
      handle: 'the-midnight-adventures-6-everywear-short',
      id: '0a68ef11a18e1fa2864d82514f4f3f30',
      imageUrl:
        'https://cdn.shopify.com/s/files/1/0077/0432/products/Tropical_Breeze__Performance-Polo__582214-03_Midnight_Adventures_6__Everywear_Stretch__LS_029211-03_22_600x600.webp?v=1670512430',
      intellisuggestData:
        'eJwEwN0NgCAMBOBbqElbOCzj8GPUJyO6f_weVkZCTLVivUhnHpJtUBqzytx12BZRvSne814f1KubiSaHwaEgC451zT8AAP__q6ARfw',
      intellisuggestSignature: '40f1de817c276745a61df1ca38097753cda0cb7d2a1424721828807ce15d3054',
      mfield_custom_fields_inseam_text: '6&quot;',
      msrp: '64.5',
      name: 'The Midnight Adventures 6&quot; (Everywear Stretch)',
      price: '64.5',
      product_type_unigram: 'adventures',
      sku: '029211-032',
      ss_available: '1',
      ss_inventory_count: '4332',
      ss_sizes:
        '[{&quot;label&quot;:&quot;S&quot;,&quot;variant_id&quot;:31735230005321,&quot;available&quot;:471},{&quot;label&quot;:&quot;M&quot;,&quot;variant_id&quot;:31735230038089,&quot;available&quot;:1460},{&quot;label&quot;:&quot;L&quot;,&quot;variant_id&quot;:31735230070857,&quot;available&quot;:1049},{&quot;label&quot;:&quot;XL&quot;,&quot;variant_id&quot;:31735230103625,&quot;available&quot;:820},{&quot;label&quot;:&quot;XXL&quot;,&quot;variant_id&quot;:31735230136393,&quot;available&quot;:532}]',
      ss_tags: [
        '1.9.2020',
        '6incheverywear2.0desc',
        'allproductsnogiftcards',
        'auto:lowinventory',
        'availablein',
        'basicsale30',
        'blackswatch',
        'bundlecasualshorts',
        'buy2bundle',
        'casualbestsellers',
        'casualbestsellers',
        'casualcombo',
        'casualbestsellersale',
        'casualbottomsfp',
        'casualbundle',
        'category:shorts',
        'ces',
        'collection:everyweargolfcollection',
        'colorapplication:solid',
        'everydaybasics',
        'everywearathl21',
        'everywearshorts',
        'extra30',
        'fabric:everywear',
        'filtercolor:black',
        'filterinseam:6&quot;',
        'fpcasualbottoms',
        'fullpricebundle',
        'golf',
        'golfdad',
        'holidaycasualpromo',
        'influencercasual',
        'lining:noliner',
        'onsitecasual',
        'otb:pfd',
        'restocked',
        'season:sp21',
        'silhouette:everywear',
        'sitebundle',
        'sitewide30',
        'sitewide30',
        'skuonsite',
        'stretchcasualdesc',
        'style:everywearshorts6',
        'swatchloadcasual',
        'tailgate21',
        'type:hybrid',
        'ycrf_casual',
        'ygroup_everywear',
      ],
      tags: [
        '1.9.2020',
        '6incheverywear2.0desc',
        'allproductsnogiftcards',
        'auto:low-inventory',
        'available in',
        'BASICSALE30',
        'blackswatch',
        'bundle--casual-shorts',
        'Buy2Bundle',
        'casual-best-sellers',
        'casual-bestsellers',
        'casual-combo',
        'casualbestseller-sale',
        'casualbottoms-FP',
        'CASUALBUNDLE',
        'CATEGORY: SHORTS',
        'CES',
        'COLLECTION:everywear-golf-collection',
        'ColorApplication:SOLID',
        'everyday-basics',
        'everywearathl21',
        'everywearshorts',
        'EXTRA30',
        'Fabric:EVERYWEAR',
        'filter-color:black',
        'filter-inseam:6&quot;',
        'FPCasualBottoms',
        'FULLPRICEBUNDLE',
        'golf',
        'golf-dad',
        'HOLIDAYCASUALPROMO',
        'influencer-casual',
        'Lining:NO LINER',
        'onsite-casual',
        'OTB: PFD',
        'restocked',
        'Season:SP21',
        'Silhouette:EVERYWEAR',
        'sitebundle',
        'SITEWIDE-30',
        'sitewide30',
        'sku-onsite',
        'stretchcasualdesc',
        'style:everywear-shorts-6',
        'SWATCHLOAD-CASUAL',
        'tailgate21',
        'Type:HYBRID',
        'YCRF_CASUAL',
        'YGroup_EVERYWEAR',
      ],
      tags_filter_color: ['black'],
      tags_filter_inseam: ['6&quot;'],
      thumbnailImageUrl:
        'https://cdn.shopify.com/s/files/1/0077/0432/products/Tropical_Breeze__Performance-Polo__582214-03_Midnight_Adventures_6__Everywear_Stretch__LS_029211-03_22_600x600.webp?v=1670512430',
      uid: '4531361710153',
      url: 'https://chubbies.myshopify.com/products/the-midnight-adventures-6-everywear-short',
      variant_id: [
        '31735230005321',
        '31735230038089',
        '31735230070857',
        '31735230103625',
        '31735230136393',
      ],
      variant_inventory_policy: 'deny',
      variant_inventory_quantity: ['471', '1460', '1049', '820', '532'],
      variant_size: ['S', 'M', 'L', 'XL', 'XXL'],
      variant_title: ['S', 'M', 'L', 'XL', 'XXL'],
    },
    {
      brand: 'Chubbies Shorts',
      handle: 'the-worlds-grayest-6-everywear-short',
      id: '49402e32fc1b2a05703f47c3a5d01c5c',
      imageUrl:
        'https://cdn.shopify.com/s/files/1/0077/0432/products/WORLD_S_GRAYEST_6_EVERYWEAR_SHORT__LS_029211-04_5151_600x600.webp?v=1670529423',
      intellisuggestData:
        'eJwEwN0NgzAMBOBbyJLt-FJnnPxULU-IwP7iu9iYBbnUqo0qgzElbFI6Q2V9ddons3lX3P9zP1BvbiYaDkOBgqz47WO9AQAA__-rvRGB',
      intellisuggestSignature: 'e1d865408ad82a4573bcd24bf636e9a656282c6073cbd95b7eb09b0f39a092c8',
      mfield_custom_fields_inseam_text: '6&quot;',
      msrp: '64.5',
      name: "The World's Grayest 6&quot; (Everywear Stretch)",
      price: '64.5',
      product_type_unigram: 'grayest',
      sku: '029211-042',
      ss_available: '1',
      ss_inventory_count: '4089',
      ss_sizes:
        '[{&quot;label&quot;:&quot;S&quot;,&quot;variant_id&quot;:31855923888201,&quot;available&quot;:363},{&quot;label&quot;:&quot;M&quot;,&quot;variant_id&quot;:31855923920969,&quot;available&quot;:1250},{&quot;label&quot;:&quot;L&quot;,&quot;variant_id&quot;:31855923953737,&quot;available&quot;:1472},{&quot;label&quot;:&quot;XL&quot;,&quot;variant_id&quot;:31855923986505,&quot;available&quot;:633},{&quot;label&quot;:&quot;XXL&quot;,&quot;variant_id&quot;:31855924019273,&quot;available&quot;:371}]',
      ss_tags: [
        '1.4.2020',
        '6incheverywear2.0desc',
        'allproductsnogiftcards',
        'auto:lowinventory',
        'availablein',
        'basicsale30',
        'bbqattire',
        'bundlecasualshorts',
        'buy2bundle',
        'casualbestsellers',
        'casualcombo',
        'casualbestsellersale',
        'casualbottomsfp',
        'casualbundle',
        'category:shorts',
        'ces',
        'collection:everyweargolfcollection',
        'colorapplication:solid',
        'ctltest',
        'escape',
        'everydaybasics',
        'everywearathl21',
        'everywearshorts',
        'extra30',
        'fabric:everywear',
        'filtercolor:grey',
        'filterinseam:6&quot;',
        'fpcasualbottoms',
        'fullpricebundle',
        'giftbundle21',
        'giftbundle21casual',
        'golf',
        'holidaycasualpromo',
        'influencercasual',
        'lining:noliner',
        'onsitecasual',
        'otb:pfd',
        'presale',
        'season:sp21',
        'shortsforlake',
        'silhouette:everywear',
        'silverliningsswatch',
        'sitebundle',
        'sitewide30',
        'sitewide30',
        'skuonsite',
        'springbreak',
        'stretchcasualdesc',
        'style:everywearshorts6',
        'swatchloadcasual',
        'tailgate21',
        'type:hybrid',
        'vacationer',
        'ycrf_casual',
        'ygroup_everywear',
      ],
      tags: [
        '1.4.2020',
        '6incheverywear2.0desc',
        'allproductsnogiftcards',
        'auto:low-inventory',
        'available in',
        'BASICSALE30',
        'BBQAttire',
        'bundle--casual-shorts',
        'Buy2Bundle',
        'casual-bestsellers',
        'casual-combo',
        'casualbestseller-sale',
        'casualbottoms-FP',
        'CASUALBUNDLE',
        'CATEGORY: SHORTS',
        'CES',
        'COLLECTION:everywear-golf-collection',
        'ColorApplication:SOLID',
        'ctl-test',
        'escape',
        'everyday-basics',
        'everywearathl21',
        'everywearshorts',
        'EXTRA30',
        'Fabric:EVERYWEAR',
        'filter-color:grey',
        'filter-inseam:6&quot;',
        'FPCasualBottoms',
        'FULLPRICEBUNDLE',
        'giftbundle21',
        'giftbundle21casual',
        'golf',
        'HOLIDAYCASUALPROMO',
        'influencer-casual',
        'Lining:NO LINER',
        'onsite-casual',
        'OTB: PFD',
        'presale',
        'Season:SP21',
        'shorts-for-lake',
        'Silhouette:EVERYWEAR',
        'silverliningsswatch',
        'sitebundle',
        'SITEWIDE-30',
        'sitewide30',
        'sku-onsite',
        'spring-break',
        'stretchcasualdesc',
        'style:everywear-shorts-6',
        'SWATCHLOAD-CASUAL',
        'tailgate21',
        'Type:HYBRID',
        'vacationer',
        'YCRF_CASUAL',
        'YGroup_EVERYWEAR',
      ],
      tags_filter_color: ['grey'],
      tags_filter_inseam: ['6&quot;'],
      thumbnailImageUrl:
        'https://cdn.shopify.com/s/files/1/0077/0432/products/WORLD_S_GRAYEST_6_EVERYWEAR_SHORT__LS_029211-04_5151_600x600.webp?v=1670529423',
      uid: '4581696536649',
      url: 'https://chubbies.myshopify.com/products/the-worlds-grayest-6-everywear-short',
      variant_id: [
        '31855923888201',
        '31855923920969',
        '31855923953737',
        '31855923986505',
        '31855924019273',
      ],
      variant_inventory_policy: 'deny',
      variant_inventory_quantity: ['363', '1250', '1472', '633', '371'],
      variant_size: ['S', 'M', 'L', 'XL', 'XXL'],
      variant_title: ['S', 'M', 'L', 'XL', 'XXL'],
    },
    {
      brand: 'Chubbies Shorts',
      handle: 'the-khakinators-5-5',
      id: 'ef8a40052f6657a33ebcdbc95d43f6d8',
      imageUrl:
        'https://cdn.shopify.com/s/files/1/0077/0432/products/KHAKINATORS_5.5_OB_001089-01_0866_600x600.webp?v=1669577686',
      intellisuggestData:
        'eJwEwN0NgzAMBOBbyNJda6fOOPmpgCdEYH_xXVEjv8hJFfViPXyYa4S1cNr8c-iXWT-NuPdzPSDFrEYJgoOIKNjWMd8AAAD__6ulEYE',
      intellisuggestSignature: 'e121c5dcec0c29e26ccfedcc4b6939a75bdbbda6995410b97b6a5c19860c34e6',
      mfield_custom_fields_inseam_text: '4&quot;|###|5.5&quot;|###|7&quot;',
      msrp: '59.5',
      name: 'The Khakinators 5.5&quot;(Stretch)',
      price: '59.5',
      product_type_unigram: 'khakinators',
      sku: '001089-011',
      ss_available: '1',
      ss_inventory_count: '5825',
      ss_sizes:
        '[{&quot;label&quot;:&quot;XS&quot;,&quot;variant_id&quot;:31210076438601,&quot;available&quot;:248},{&quot;label&quot;:&quot;S&quot;,&quot;variant_id&quot;:379784790017,&quot;available&quot;:1382},{&quot;label&quot;:&quot;M&quot;,&quot;variant_id&quot;:379784822785,&quot;available&quot;:1144},{&quot;label&quot;:&quot;L&quot;,&quot;variant_id&quot;:379784855553,&quot;available&quot;:881},{&quot;label&quot;:&quot;XL&quot;,&quot;variant_id&quot;:379784888321,&quot;available&quot;:902},{&quot;label&quot;:&quot;XXL&quot;,&quot;variant_id&quot;:379784921089,&quot;available&quot;:662},{&quot;label&quot;:&quot;XXXL&quot;,&quot;variant_id&quot;:31210076733513,&quot;available&quot;:606}]',
      ss_tags: [
        '5.5shortextendedsizing',
        '5originalstretch',
        '5originalstretchdesc',
        'allproductsnogiftcards',
        'auto:lowinventory',
        'availablein',
        'backtoschool',
        'basicsale30',
        'bestseller',
        'bestseller2019',
        'bfexclusives',
        'bfshortssale',
        'bogo',
        'bogocampfire',
        'bts21casual',
        'bundlecasualshorts',
        'bundleable',
        'bundlepfd5',
        'buy2bundle',
        'casualbestsellers',
        'casualbestsellers',
        'casual20',
        'casualbestseller',
        'casualbestsellersale',
        'casualbottomsfp',
        'casualbundle',
        'casualfacebookshop',
        'category:shorts',
        'colorapplication:solid',
        'coo:mexico',
        'ctltest',
        'everydaybasics',
        'extra30',
        'fabricdetail:97cotton3lycra',
        'fabric:stretchtwill',
        'facebookdpa',
        'fathersday21',
        'filtercolor:beige',
        'filtercolor:khaki',
        'filterfabric:khaki',
        'filterfabric:stretch',
        'filterinseam:5.5&quot;',
        'fpcasualbottoms',
        'franchise:basic',
        'fullpricebundle',
        'giftsfordads',
        'golfcorestretch',
        'highestrated',
        'holidaycasualpromo',
        'imu:49.5',
        'influencercasual',
        'influencersku',
        'inventoryfullstock',
        'khaki',
        'khakicollection',
        'khakinatorswatch',
        'l',
        'lining:noliner',
        'loopreturns',
        'onsitecasual',
        'otb:pfd',
        'print:solid',
        'season:basic',
        'seconds',
        'silhouette:originalshort(5.5&quot;inseam)',
        'silhouette:original',
        'sitebundle',
        'sitewide30',
        'sitewide30',
        'skuonsite',
        'springbreak',
        'stretchcasualdesc',
        'style:the55inseamstretchshorts',
        'subcategory:originalshort',
        'swatchloadcasual',
        'trendingjune2020',
        'twill25',
        'type:elastic',
        'under50',
        'vendor:monty',
        'whsl',
        'wt',
        'xxl',
        'xxxl',
        'ycrf_casual',
        'ygroup_original',
      ],
      tags: [
        '5.5shortextendedsizing',
        '5originalstretch',
        '5originalstretchdesc',
        'allproductsnogiftcards',
        'auto:low-inventory',
        'available in',
        'backtoschool',
        'BASICSALE30',
        'bestseller',
        'bestseller2019',
        'BFexclusives',
        'bfshortssale',
        'BOGO',
        'bogocampfire',
        'BTS21-Casual',
        'bundle--casual-shorts',
        'bundleable',
        'bundlepfd5',
        'Buy2Bundle',
        'casual-best-sellers',
        'casual-bestsellers',
        'casual20',
        'casualbestseller',
        'casualbestseller-sale',
        'casualbottoms-FP',
        'CASUALBUNDLE',
        'casualfacebookshop',
        'CATEGORY: SHORTS',
        'ColorApplication:SOLID',
        'COO: MEXICO',
        'ctl-test',
        'everyday-basics',
        'EXTRA30',
        'FABRIC DETAIL: 97 COTTON 3 LYCRA',
        'Fabric:STRETCH TWILL',
        'facebookdpa',
        'fathersday21',
        'filter-color:beige',
        'filter-color:khaki',
        'filter-fabric:Khaki',
        'filter-fabric:stretch',
        'filter-inseam:5.5&quot;',
        'FPCasualBottoms',
        'FRANCHISE: BASIC',
        'FULLPRICEBUNDLE',
        'giftsfordads',
        'golfcorestretch',
        'highestrated',
        'HOLIDAYCASUALPROMO',
        'IMU: 49.5',
        'influencer-casual',
        'influencer-sku',
        'INVENTORYFULLSTOCK',
        'Khaki',
        'khakicollection',
        'khakinatorswatch',
        'L',
        'Lining:NO LINER',
        'loopreturns',
        'onsite-casual',
        'OTB: PFD',
        'PRINT: SOLID',
        'Season:BASIC',
        'seconds',
        'SILHOUETTE: ORIGINAL SHORT (5.5&quot; INSEAM)',
        'Silhouette:ORIGINAL',
        'sitebundle',
        'SITEWIDE-30',
        'sitewide30',
        'sku-onsite',
        'spring-break',
        'stretchcasualdesc',
        'style:the-5-5-inseam-stretch-shorts',
        'SUB CATEGORY: ORIGINAL SHORT',
        'SWATCHLOAD-CASUAL',
        'trendingjune2020',
        'Twill25',
        'Type:ELASTIC',
        'under50',
        'VENDOR: MONTY',
        'WHSL',
        'WT',
        'XXL',
        'XXXL',
        'YCRF_CASUAL',
        'YGroup_ORIGINAL',
      ],
      tags_filter_color: ['beige', 'khaki'],
      tags_filter_inseam: ['5.5&quot;'],
      thumbnailImageUrl:
        'https://cdn.shopify.com/s/files/1/0077/0432/products/KHAKINATORS_5.5_OB_001089-01_0866_600x600.webp?v=1669577686',
      uid: '75784683521',
      url: 'https://chubbies.myshopify.com/products/the-khakinators-5-5',
      variant_id: [
        '31210076438601',
        '379784790017',
        '379784822785',
        '379784855553',
        '379784888321',
        '379784921089',
        '31210076733513',
      ],
      variant_inventory_policy: 'deny',
      variant_inventory_quantity: ['248', '1382', '1144', '881', '902', '662', '606'],
      variant_size: ['XS', 'S', 'M', 'L', 'XL', 'XXL', 'XXXL'],
      variant_title: ['XS', 'S', 'M', 'L', 'XL', 'XXL', 'XXXL'],
    },
    {
      brand: 'Chubbies Shorts',
      handle: 'the-schwort-5-5-lightweight',
      id: '1b8e8f36f407bcb2ff35c675814f1174',
      imageUrl:
        'https://cdn.shopify.com/s/files/1/0077/0432/products/Schworts-2.0_5.5_008042-05_600x600.webp?v=1668114448',
      intellisuggestData:
        'eJwEwN0NwjAMBOBbyNI5-IIzTn4Q8FQ17f7qd6opX8hFrz6qDcW08CnrCtr6cPo7s5VOXL9j3yCTUYwqcAiEVPHd__UEAAD__6vGEYM',
      intellisuggestSignature: 'ceb1d2b6d77da9fca824de5a06a5aa1c135219762b53383e588c7f03bc1fcbc3',
      mfield_custom_fields_inseam_text: '5.5&quot;|###|7&quot;|###|30&quot;',
      msrp: '39.5',
      name: 'The Schwort 5.5&quot; (Schwort)',
      price: '39.5',
      product_type_unigram: 'schwort',
      sku: '008042-052',
      ss_available: '1',
      ss_inventory_count: '2598',
      ss_sizes:
        '[{&quot;label&quot;:&quot;S&quot;,&quot;variant_id&quot;:20001096302665,&quot;available&quot;:755},{&quot;label&quot;:&quot;M&quot;,&quot;variant_id&quot;:20001096335433,&quot;available&quot;:1216},{&quot;label&quot;:&quot;L&quot;,&quot;variant_id&quot;:20001096368201,&quot;available&quot;:308},{&quot;label&quot;:&quot;XL&quot;,&quot;variant_id&quot;:20001096400969,&quot;available&quot;:203},{&quot;label&quot;:&quot;XXL&quot;,&quot;variant_id&quot;:20001096433737,&quot;available&quot;:116}]',
      ss_tags: [
        '5loungeshorts',
        '5loungesoliddesc',
        '8.18.19',
        'allproductsnogiftcards',
        'auto:lowinventory',
        'availablein',
        'basicsale30',
        'buy2bundle',
        'category:shorts',
        'colorapplication:heather',
        'drawstringshort',
        'dream',
        'everydaybasics',
        'extra30',
        'fabric:frenchterry',
        'facebookdpa',
        'filtercolor:grey',
        'filterfabric:100%cotton',
        'filterinseam:5.5&quot;',
        'finishtv',
        'franchise:basic',
        'fullpricebundle',
        'giftsforcouch',
        'holidayoutfitting',
        'influencerlounge',
        'influencersku',
        'lining:noliner',
        'lounge2bundle',
        'loungebestsellers',
        'loungeschweats',
        'lounge5',
        'loungebestsellers',
        'loungeblanketbundle',
        'loungebundle',
        'loungefacebookshop',
        'loungeshortsdesc',
        'onsitelounge',
        'otb:lounge',
        'schwortswatch',
        'season:basic',
        'silhouette:schwort',
        'sitebundle',
        'sitewide30',
        'sitewide30',
        'skuonsite',
        'solid5sweatshort',
        'solidlounge',
        'solidlounge21',
        'solidsweatshorts',
        'style:solid5sweatshorts',
        'subcategory:drawstring',
        'swatchinfolounge',
        'sweatshorts',
        'terry5loungeprinteddesc',
        'type:coreloungeshorts',
        'under50gift',
        'vday2020',
        'ycrf_lounge',
        'ygroup_schwort',
      ],
      tags: [
        '5loungeshorts',
        '5loungesoliddesc',
        '8.18.19',
        'allproductsnogiftcards',
        'auto:low-inventory',
        'available in',
        'BASICSALE30',
        'Buy2Bundle',
        'CATEGORY: SHORTS',
        'ColorApplication:HEATHER',
        'DRAWSTRING SHORT',
        'dream',
        'everyday-basics',
        'EXTRA30',
        'Fabric:FRENCH TERRY',
        'facebookdpa',
        'filter-color:grey',
        'filter-fabric:100% cotton',
        'filter-inseam:5.5&quot;',
        'finishtv',
        'FRANCHISE: BASIC',
        'FULLPRICEBUNDLE',
        'giftsforcouch',
        'holiday-outfitting',
        'influencer-lounge',
        'influencer-sku',
        'Lining:NO LINER',
        'lounge-2bundle',
        'lounge-best-sellers',
        'lounge-schweats',
        'lounge5',
        'loungebestsellers',
        'loungeblanketbundle',
        'LOUNGEBUNDLE',
        'loungefacebookshop',
        'loungeshortsdesc',
        'onsite-lounge',
        'OTB: LOUNGE',
        'schwortswatch',
        'Season:BASIC',
        'Silhouette:SCHWORT',
        'sitebundle',
        'SITEWIDE-30',
        'sitewide30',
        'sku-onsite',
        'solid5sweatshort',
        'solidlounge',
        'solidlounge21',
        'solidsweatshorts',
        'style:solid-5-sweat-shorts',
        'SUB CATEGORY: DRAWSTRING',
        'SWATCHINFO-LOUNGE',
        'sweat-shorts',
        'terry5loungeprinteddesc',
        'Type:CORE LOUNGE SHORTS',
        'under50gift',
        'vday2020',
        'YCRF_LOUNGE',
        'YGroup_SCHWORT',
      ],
      tags_filter_color: ['grey'],
      tags_filter_inseam: ['5.5&quot;'],
      thumbnailImageUrl:
        'https://cdn.shopify.com/s/files/1/0077/0432/products/Schworts-2.0_5.5_008042-05_600x600.webp?v=1668114448',
      uid: '2196470267977',
      url: 'https://chubbies.myshopify.com/products/the-schwort-5-5-lightweight',
      variant_id: [
        '20001096302665',
        '20001096335433',
        '20001096368201',
        '20001096400969',
        '20001096433737',
      ],
      variant_inventory_policy: 'deny',
      variant_inventory_quantity: ['755', '1216', '308', '203', '116'],
      variant_size: ['S', 'M', 'L', 'XL', 'XXL'],
      variant_title: ['S', 'M', 'L', 'XL', 'XXL'],
    },
    {
      brand: 'Chubbies Shorts',
      handle: 'the-neon-lights-5-5-stretch-zipper-pocket',
      id: '5720ede30eef504d1dbdb665a9d6c889',
      imageUrl:
        'https://cdn.shopify.com/s/files/1/0077/0432/products/NEON_LIGHTS_5.5_STRETCH_ZIPPER_POCKET__SD_109201-01_5814_600x600.webp?v=1668263692',
      intellisuggestData:
        'eJwEwN0NwjAMBOBbyNJdiI0zTn4Q8FQ17f7qd3rzfCEXFRphw-u0qunWvdLWh1PvzFY6cf2OfUNshTJKEAKEe-C7_-sJAAD__6tyEX4',
      intellisuggestSignature: '31a4b239fef1836bf92c601ea784eb137c14c954b2f5a332f0b89b14a47cf7f4',
      mfield_custom_fields_inseam_text: '4&quot;|###|5.5&quot;|###|7&quot;',
      msrp: '69.5',
      name: 'The Neon Lights 5.5&quot;  (Classic Swim Trunk)',
      price: '69.5',
      product_type_unigram: 'lights',
      sku: '109201-011',
      ss_available: '1',
      ss_inventory_count: '6083',
      ss_sizes:
        '[{&quot;label&quot;:&quot;XS&quot;,&quot;variant_id&quot;:31206692520009,&quot;available&quot;:171},{&quot;label&quot;:&quot;S&quot;,&quot;variant_id&quot;:31206692552777,&quot;available&quot;:1200},{&quot;label&quot;:&quot;M&quot;,&quot;variant_id&quot;:31206692585545,&quot;available&quot;:2045},{&quot;label&quot;:&quot;L&quot;,&quot;variant_id&quot;:31206692618313,&quot;available&quot;:1320},{&quot;label&quot;:&quot;XL&quot;,&quot;variant_id&quot;:31206692651081,&quot;available&quot;:635},{&quot;label&quot;:&quot;XXL&quot;,&quot;variant_id&quot;:31206692683849,&quot;available&quot;:367},{&quot;label&quot;:&quot;XXXL&quot;,&quot;variant_id&quot;:31206692716617,&quot;available&quot;:345}]',
      ss_tags: [
        '2.2.20',
        '2020newswim',
        '2020thighberproducts',
        '5.5trunkextendedsizing',
        '5classictrunk',
        '5inchzipperswim',
        '5stretchtrunk',
        '__discountamtmsg:buy2selectfullpriceswimtrunks&amp;save$10',
        '__discountctamsg:offerappliedincart',
        'allproductsnogiftcards',
        'allswimtrunksdesc',
        'auto:lowinventory',
        'availablein',
        'banner_tag:buy2save$10||#f07ad7',
        'basicprint',
        'basicsale30',
        'basicsswim2020',
        'bundles',
        'category:swim',
        'colorapplication:print',
        'combinedfacebookshop',
        'deletefathersday',
        'escape',
        'extra30',
        'fabric:4waystretch',
        'fathersday21',
        'filtercolor:blue',
        'filterfabric:stretch',
        'filterinseam:5.5&quot;',
        'fpswim',
        'franchise:basic',
        'fullpriceswim',
        'fullpricebundle',
        'fullpriceswim',
        'giftbundle21',
        'giftbundle21swim',
        'giftguide2020',
        'holidayoutfitting',
        'holidayswimpromo',
        'influencersku',
        'influencerswim',
        'inventoryfullstock',
        'kaymay13',
        'lining:noliner',
        'loopreturns',
        'matching2022',
        'neonlights',
        'neonlights2020',
        'neonlightsswatch',
        'onsiteswim',
        'otb:swim',
        'poolsidemeet',
        'postcrash',
        'powermatchingsets',
        'season:basic',
        'shortsforlake',
        'silhouette:stretchoriginalswimtrunk',
        'sitebundle',
        'sitewide30',
        'sitewide30',
        'skuonsite',
        'stretchswim',
        'style:5inchinseamstretchswimtrunks',
        'subcategory:stretchswim',
        'swatchinfoswim',
        'swim',
        'swimbestsellers',
        'swimbestsellerssale',
        'swimbestsellers2020',
        'swimbundle',
        'swimfacebookshop',
        'swimflashsale30',
        'texttag:buy2selectfullpriceswimtrunks&amp;save$10||#f07ad7',
        'theclassicswimtrunks',
        'trendingjune2020',
        'type:coretrunk',
        'ultimateswimsale',
        'vacationer',
        'vday2020',
        'xxxl',
        'ycrf_swim',
        'ygroup_stretchoriginalswimtrunk',
      ],
      tags: [
        '2.2.20',
        '2020newswim',
        '2020thighberproducts',
        '5.5trunkextendedsizing',
        '5classictrunk',
        '5inchzipperswim',
        '5stretchtrunk',
        '__discount-amt-msg:BUY 2 SELECT FULL PRICE SWIM TRUNKS &amp; SAVE $10',
        '__discount-cta-msg:Offer Applied in Cart',
        'allproductsnogiftcards',
        'allswimtrunksdesc',
        'auto:low-inventory',
        'available in',
        'banner_tag: BUY 2 SAVE $10 || #F07AD7',
        'basic-print',
        'BASICSALE30',
        'basicsswim2020',
        'bundles',
        'CATEGORY: SWIM',
        'ColorApplication:PRINT',
        'combinedfacebookshop',
        'deletefathersday',
        'escape',
        'EXTRA30',
        'Fabric:4-WAY STRETCH',
        'fathersday21',
        'filter-color:blue',
        'filter-fabric:stretch',
        'filter-inseam:5.5&quot;',
        'FPSwim',
        'FRANCHISE: BASIC',
        'FULLPRICE-SWIM',
        'FULLPRICEBUNDLE',
        'FULLPRICESWIM',
        'giftbundle21',
        'giftbundle21swim',
        'giftguide2020',
        'holiday-outfitting',
        'HOLIDAYSWIMPROMO',
        'influencer-sku',
        'influencer-swim',
        'INVENTORYFULLSTOCK',
        'kaymay13',
        'Lining:NO LINER',
        'loopreturns',
        'matching2022',
        'neonlights',
        'neonlights2020',
        'neonlightsswatch',
        'onsite-swim',
        'OTB: SWIM',
        'poolsidemeet',
        'postcrash',
        'power-matching-sets',
        'Season:BASIC',
        'shorts-for-lake',
        'Silhouette:STRETCH ORIGINAL SWIM TRUNK',
        'sitebundle',
        'SITEWIDE-30',
        'sitewide30',
        'sku-onsite',
        'stretchswim',
        'style:5-inch-inseam-stretch-swim-trunks',
        'SUB CATEGORY: STRETCH SWIM',
        'SWATCHINFO-SWIM',
        'SWIM',
        'swim-bestsellers',
        'swimbestsellers-sale',
        'swimbestsellers2020',
        'SWIMBUNDLE',
        'swimfacebookshop',
        'SWIMFLASHSALE30',
        'texttag:BUY 2 SELECT FULL PRICE SWIM TRUNKS &amp; SAVE $10 || #F07AD7',
        'theclassicswimtrunks',
        'trendingjune2020',
        'Type:CORE TRUNK',
        'ultimate-swim-sale',
        'vacationer',
        'vday2020',
        'XXXL',
        'YCRF_SWIM',
        'YGroup_STRETCH-ORIGINAL-SWIM-TRUNK',
      ],
      tags_filter_color: ['blue'],
      tags_filter_inseam: ['5.5&quot;'],
      thumbnailImageUrl:
        'https://cdn.shopify.com/s/files/1/0077/0432/products/NEON_LIGHTS_5.5_STRETCH_ZIPPER_POCKET__SD_109201-01_5814_600x600.webp?v=1668263692',
      uid: '4374465183817',
      url: 'https://chubbies.myshopify.com/products/the-neon-lights-5-5-stretch-zipper-pocket',
      variant_id: [
        '31206692520009',
        '31206692552777',
        '31206692585545',
        '31206692618313',
        '31206692651081',
        '31206692683849',
        '31206692716617',
      ],
      variant_inventory_policy: 'deny',
      variant_inventory_quantity: ['171', '1200', '2045', '1320', '635', '367', '345'],
      variant_size: ['XS', 'S', 'M', 'L', 'XL', 'XXL', 'XXXL'],
      variant_title: ['XS', 'S', 'M', 'L', 'XL', 'XXL', 'XXXL'],
    },
  ],
  facets: [
    {
      field: 'ss_price',
      label: 'Price',
      type: 'slider',
      collapse: 0,
      step: 5,
      facet_active: 0,
      active: [15, 120],
      range: [15, 120],
      values: [],
    },
    {
      field: 'variant_size',
      label: 'Size',
      type: 'grid',
      collapse: 0,
      facet_active: 0,
      values: [
        {
          active: false,
          type: 'value',
          value: '30',
          label: '30',
          count: 23,
        },
        {
          active: false,
          type: 'value',
          value: '32',
          label: '32',
          count: 23,
        },
        {
          active: false,
          type: 'value',
          value: '33',
          label: '33',
          count: 23,
        },
        {
          active: false,
          type: 'value',
          value: '34',
          label: '34',
          count: 23,
        },
        {
          active: false,
          type: 'value',
          value: '35',
          label: '35',
          count: 23,
        },
        {
          active: false,
          type: 'value',
          value: '36',
          label: '36',
          count: 23,
        },
        {
          active: false,
          type: 'value',
          value: '38',
          label: '38',
          count: 23,
        },
        {
          active: false,
          type: 'value',
          value: '40',
          label: '40',
          count: 23,
        },
        {
          active: false,
          type: 'value',
          value: 'XS',
          label: 'XS',
          count: 36,
        },
        {
          active: false,
          type: 'value',
          value: 'S',
          label: 'S',
          count: 532,
        },
        {
          active: false,
          type: 'value',
          value: 'M',
          label: 'M',
          count: 532,
        },
        {
          active: false,
          type: 'value',
          value: 'L',
          label: 'L',
          count: 532,
        },
        {
          active: false,
          type: 'value',
          value: 'XL',
          label: 'XL',
          count: 532,
        },
        {
          active: false,
          type: 'value',
          value: 'XXL',
          label: 'XXL',
          count: 530,
        },
        {
          active: false,
          type: 'value',
          value: 'XXXL',
          label: 'XXXL',
          count: 34,
        },
      ],
    },
    {
      field: 'tags_filter_color',
      label: 'Color',
      type: 'palette',
      collapse: 0,
      facet_active: 0,
      values: [
        {
          active: false,
          type: 'value',
          value: 'blue',
          label: 'blue',
          count: 164,
        },
        {
          active: false,
          type: 'value',
          value: 'black',
          label: 'black',
          count: 97,
        },
        {
          active: false,
          type: 'value',
          value: 'grey',
          label: 'grey',
          count: 61,
        },
        {
          active: false,
          type: 'value',
          value: 'green',
          label: 'green',
          count: 37,
        },
        {
          active: false,
          type: 'value',
          value: 'white',
          label: 'white',
          count: 34,
        },
        {
          active: false,
          type: 'value',
          value: 'pink',
          label: 'pink',
          count: 24,
        },
        {
          active: false,
          type: 'value',
          value: 'beige',
          label: 'beige',
          count: 22,
        },
        {
          active: false,
          type: 'value',
          value: 'multi',
          label: 'multi',
          count: 21,
        },
        {
          active: false,
          type: 'value',
          value: 'red',
          label: 'red',
          count: 19,
        },
        {
          active: false,
          type: 'value',
          value: 'brown',
          label: 'brown',
          count: 17,
        },
        {
          active: false,
          type: 'value',
          value: 'khaki',
          label: 'khaki',
          count: 12,
        },
        {
          active: false,
          type: 'value',
          value: 'purple',
          label: 'purple',
          count: 9,
        },
        {
          active: false,
          type: 'value',
          value: 'yellow',
          label: 'yellow',
          count: 7,
        },
      ],
    },
  ],
  breadcrumbs: [
    {
      field: '',
      label: 'Search: "short"',
      filterLabel: 'Search',
      filterValue: 'short',
      removeFilters: [],
      removeRefineQuery: [],
    },
  ],
  filterSummary: [],
  merchandising: {
    redirect: '',
    is_elevated: [
      '8c039cbaa52f178ff18ef936600bfac2',
      '0a68ef11a18e1fa2864d82514f4f3f30',
      'a30366f307331796a1d329fa96526b79',
      '49402e32fc1b2a05703f47c3a5d01c5c',
      'ef8a40052f6657a33ebcdbc95d43f6d8',
      '1b8e8f36f407bcb2ff35c675814f1174',
      '5720ede30eef504d1dbdb665a9d6c889',
      'b4afbdca37c855d5c9008b4628ab8723',
    ],
    elevated: [],
    removed: [],
    content: {},
    facets: [],
    facetsHide: [],
    experiments: [],
    variants: [],
    personalized: false,
    triggeredCampaigns: [
      {
        id: '66a4dc43bc3f51d567ab627e1acb4cdc',
        title: '',
        type: '',
      },
      {
        id: '141937',
        title: 'Global',
        type: 'global',
      },
    ],
  },
}
